INSERT INTO bookmarks (title, url, created_at) VALUES
('Java Tutorial - Official Documentation', 'https://docs.oracle.com/javase/tutorial/', CURRENT_TIMESTAMP()),
('Baeldung - In-depth Java Tutorials', 'https://www.baeldung.com/', CURRENT_TIMESTAMP()),
('Java Magazine - Advanced Features', 'https://docs.oracle.com/en/java/', CURRENT_TIMESTAMP()),
('Stack Overflow - Q&A for Java Developers', 'https://stackoverflow.com/questions/tagged/java', CURRENT_TIMESTAMP()),
('GitHub - Open Source Java Code Repository', 'https://github.com/Index', CURRENT_TIMESTAMP()),
('Maven Repository - Download Java Libraries', 'https://search.maven.org/?eh', CURRENT_TIMESTAMP()),
('Javarevisited - Tutorials and Tips', 'https://javarevisited.blogspot.com/', CURRENT_TIMESTAMP()),
('DZone Java - Articles and Tutorials', 'https://dzone.com/java', CURRENT_TIMESTAMP()),
('InfoQ Java - Enterprise Development News', 'https://www.infoq.com/java/', CURRENT_TIMESTAMP()),
('CodeGym - Interactive Java Course', 'https://codegym.cc/', CURRENT_TIMESTAMP()),
('The Java™ Tutorials - More Interactive Tutorials', 'https://docs.oracle.com/javase/tutorial/', CURRENT_TIMESTAMP()),
('Tutorialspoint Java - Tutorials and References', 'https://www.javatpoint.com/', CURRENT_TIMESTAMP()),
('Programiz Java - Tutorials and Exercises', 'https://www.programiz.com/java-programming', CURRENT_TIMESTAMP()),
('GeeksforGeeks Java - Interview Questions', 'https://www.geeksforgeeks.org/core-java-interview-questions-for-freshers/', CURRENT_TIMESTAMP()),
('CodinGame Java - Coding Challenges', 'https://www.codingame.com/work/java-interview-questions/', CURRENT_TIMESTAMP()),
('LeetCode Java - Coding Practice Problems', 'https://leetcode.com/problemset/', CURRENT_TIMESTAMP()),
('HackerRank Java - Coding Challenges', 'https://www.hackerrank.com/domains/java', CURRENT_TIMESTAMP()),
('jOOQ - SQL Generation Library', 'https://www.jooq.org/', CURRENT_TIMESTAMP()),
('Spring - Enterprise Java Framework', 'https://spring.io/', CURRENT_TIMESTAMP()),
('Jakarta EE - Java Enterprise Development', 'https://projects.eclipse.org/projects/ee4j.jakartaee-platform', CURRENT_TIMESTAMP());
